### ISSUE TITLE
Error caused by field or characters or something in text

### ISSUE THREAD

**Issue by AlisterH** [EZUSoft/AnotherDXF2Shape#15]
I have isolated some text (with a field in it) that causes the import to fail - see
[testtb.zip](https://github.com/EZUSoft/AnotherDXF2Shape/files/4156801/testtb.zip)
```
An error has occurred while executing Python code: 

ValueError: invalid literal for int() with base 10: 'OUNCIL200204 PLAN CHANGE DRAWINGS NZTM SHAPE FILESTESTTB.DXF' 
Traceback (most recent call last):
  File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AnotherDXF2Shape\uiADXF2Shape.py", line 730, in btnStart_clicked
    Antw = DXFImporter (self, "SHP", self.listDXFDatNam, ZielPfad, self.chkSHP.isChecked(), self.cbCharSet.currentText(),self.chkCol.isChecked(),self.chkLay.isChecked(), self.chkUseTextFormat.isChecked(), self.chkUseColor4Point.isChecked(), self.chkUseColor4Line.isChecked(), self.chkUseColor4Poly.isChecked(), dblFaktor, self.chkTransform.isChecked(), DreiPassPunkte, self.chk3D.isChecked())
  File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AnotherDXF2Shape\clsDXFTools.py", line 506, in DXFImporter
    Antw = EineDXF (uiParent, mLay.crs(), bZielSave, sOutForm, grpProjekt, AktList, Kern, AktOpt, AktDXFDatNam, zielPfadOrDatei, qPrjDatName, sCharSet, bLayer, bFormatText, bUseColor4Point,bUseColor4Line,bUseColor4Poly, dblFaktor, okTransform, DreiPassPunkte, bGen3D)
  File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AnotherDXF2Shape\clsDXFTools.py", line 641, in EineDXF
    attTableEdit(sOutForm,korrSHPDatNam,bFormatText,sCharSet)
  File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AnotherDXF2Shape\clsDBase.py", line 460, in attTableEdit
    color=hex(int(color[1:])).replace('0x','#')
ValueError: invalid literal for int() with base 10: 'OUNCIL200204 PLAN CHANGE DRAWINGS NZTM SHAPE FILESTESTTB.DXF'
```

**Comment by EZUSoft** [comment]
Thanks for the feedback.
Version [1.1.4](https://plugins.qgis.org/plugins/AnotherDXF2Shape/version/1.1.4/) should solve the problem.
