### ISSUE TITLE
Uncaught UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 20: ordinal not in range(128)


### ISSUE THREAD

**Issue by peter-shr** [EZUSoft/AnotherDXF2Shape#5]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/user/.qgis2/python/plugins\AnotherDXF2Shape\uiADXF2Shape.py", line 445, in btnStart_clicked
    Antw = DXFImporter (self, self.listDXFDatNam, ZielPfad, self.chkSHP.isChecked(), self.cbCharSet.currentText(),self.chkCol.isChecked(),self.chkLay.isChecked(), self.chkUseTextFormat.isChecked(), self.chkUseColor4Point.isChecked(), self.chkUseColor4Line.isChecked(), self.chkUseColor4Poly.isChecked(), dblFaktor)
  File "C:/Users/user/.qgis2/python/plugins\AnotherDXF2Shape\clsDXFTools.py", line 338, in DXFImporter
    Antw = EineDXF (uiParent,grpProjekt,AktList, Kern, AktOpt, AktDXFDatNam,shpPfad, qPrjDatName, sCharSet, bLayer, bFormatText, bUseColor4Point,bUseColor4Line,bUseColor4Poly, dblFaktor)
  File "C:/Users/user/.qgis2/python/plugins\AnotherDXF2Shape\clsDXFTools.py", line 407, in EineDXF
    DBFedit(korrSHPDatNam,bFormatText)
  File "C:/Users/user/.qgis2/python/plugins\AnotherDXF2Shape\clsDBase.py", line 315, in DBFedit
    addFehler(tr('incomplete ogr_style: ') + att)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 20: ordinal not in range(128)

```
AnotherDXF2Shape 0.6, QGIS 2.14.11-Essen on Windows 10

**Comment by EZUSoft** [comment]
The current version V0.7 should solve the problem.
